name: Maket Testing

env:
    NODE_VERSION: 18.x

on: [deployment_status]

jobs:
    e2e:
        if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.sha == github.event.deployment.sha }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Get branch name
              run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
            - name: Run Cypress 🌲
              uses: cypress-io/github-action@v2
              with:
                  config-file: cypress.config.ts
                  record: true
                  timeout-minutes: 5
              env:
                  CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  COMMIT_INFO_BRANCH: ${{ env.BRANCH_NAME }}
