name: CI

on:
    push:
        branches:
            - '**'

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm ci

            - name: Build Next.js app
              run: npm run build

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm start
                  wait-on: 'http://localhost:3000'
                  record: true
                  parallel: true
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    deploy:
        runs-on: ubuntu-latest
        needs: cypress-run
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            #Changing NODE enviroment.
            - name: Install dependencies
              run: npm ci

            - name: Build Next.js app
              run: npm run build

            - name: Deploy to Vercel
              run: |
                  npm install -g vercel
                  vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
