name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        run: |
          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --confirm)
          echo "DEPLOYMENT_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Echo Deployment URL
        run: echo "Deployment URL: ${{ env.DEPLOYMENT_URL }}"

  E2E-Tests:
    needs: Deploy-Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: ${{ env.DEPLOYMENT_URL }}
          wait-on-timeout: 120
          config-file: cypress.json
        env:
          CYPRESS_BASE_URL: ${{ env.DEPLOYMENT_URL }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
