name: CI/CD

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    NODE_VERSION: 18 # Define the Node.js version as a variable

on:
    push:
        branches-ignore:
            - main

jobs:
    Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install Vercel CLI
          run: npm install --global vercel@latest
        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        - name: Build Project Artifacts
          run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        - name: Deploy Project Artifacts to Vercel
          run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }} # Use the variable

            - name: Install dependencies
              run: npm ci

            - name: Build Next.js app
              run: npm run build

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm start
                  wait-on: 'http://localhost:3000'
                  record: true
                  parallel: true
              env:
                  NODE_VERSION: ${{ env.NODE_VERSION }} # Use the variable
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
