name: Echo Branch Name

on: deployment_status

jobs:
    echoBranchName:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get and Echo Branch Name
              run: |
                  BRANCH_NAME=$(git name-rev --name-only ${{ github.sha }})
                  echo "Branch name: $BRANCH_NAME"
