name: CI

on:
    push:
        branches:
            - '**' # Trigger on push to any branch

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        env:
            NODE_VERSION: 18 # Define the Node.js version as a variable

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }} # Use the variable

            - name: Install dependencies
              run: npm ci

            - name: Build Next.js app
              run: npm run build

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm start
                  wait-on: 'http://localhost:3000'
                  record: true
                  parallel: true
              env:
                  NODE_VERSION: ${{ env.NODE_VERSION }} # Use the variable
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    deploy:
        runs-on: ubuntu-latest
        needs: cypress-run # Ensures this job only runs if the cypress-run job passes
        env:
            NODE_VERSION: 16 # Define the Node.js version as a variable

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }} # Use the variable

            - name: Install dependencies
              run: npm ci

            - name: Build Next.js app
              run: npm run build

            - name: Deploy to Vercel
              run: |
                  npm install -g vercel
                  vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
