name: Echo Branch Name

on:
    push:
        branches:
            - '**'

jobs:
    echoBranchName:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get and Echo Branch Name
              run: |
                  BRANCH_NAME=${GITHUB_REF#refs/heads/}
                  echo "Branch name: $BRANCH_NAME"
