name: E2E Testing

env:
  NODE_VERSION: 18.x
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - '**'

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Project Locally
        run: npm run build

      - name: Start Local Server
        run: npm start &
        id: start_server

      - name: Wait for Server to be Ready
        run: npx wait-on http://localhost:3000

      # Set Deployment URL step to define the environment variable (optional if you still need it for other purposes)
      - name: Set Deployment URL
        run: echo "DEPLOYMENT_URL=http://localhost:3000" >> $GITHUB_ENV

  E2E-Tests:
    needs: Deploy-Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Wait for Local Server to be Ready
        run: npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: http://localhost:3000
          parallel: true
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
