name: Maket Testing

env:
    NODE_VERSION: 18.x

on:
    push:
        branches:
            - '**'
jobs:
    captureBranchName:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Dump GitHub ref_name
              run: echo ${{ github.ref_name }}

            - name: Save branch name
              run: echo ${{ github.ref_name }} > branch_name.txt

            - name: Upload branch name artifact
              uses: actions/upload-artifact@v2
              with:
                  name: branch-name
                  path: branch_name.txt

    e2e:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.sha == github.event.deployment.sha }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Download branch name artifact
              uses: actions/download-artifact@v2
              with:
                  name: branch-name

            - name: Read branch name
              id: read_branch_name
              run: |
                  BRANCH_NAME=$(cat branch_name.txt)
                  echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

            - name: Get BRANCH_NAME
              run: echo ${{ env.BRANCH_NAME }}

            - name: Run Cypress 🌲
              uses: cypress-io/github-action@v2
              with:
                  config-file: cypress.config.ts
                  record: true
                  timeout-minutes: 5
              env:
                  CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  COMMIT_INFO_BRANCH: ${{ env.BRANCH_NAME }}
